#include "kontrolem_workbench/scaffold.hpp"

#include <sstream>

#include "kontrolem_workbench/spec_format.hpp"

namespace kontrolem_workbench
{

std::string scaffold_yaml(
  const std::string & law, const kontrolem_control::ParameterSpec & spec,
  const std::vector<std::string> & joint_names, int nq, int update_rate_hz)
{
  std::ostringstream os;
  os << "# Generated by `kontrolem_setup new` — a starting point, not a tuned config.\n"
     << "# Every " << law << " parameter is present at its DEFAULT; edit before flight.\n"
     << "# Validate edits offline with:  kontrolem_setup lint <this file> --urdf <robot.urdf>\n"
     << "controller_manager:\n"
     << "  ros__parameters:\n"
     << "    update_rate: " << update_rate_hz << "  # Hz\n\n"
     << "    joint_state_broadcaster:\n"
     << "      type: joint_state_broadcaster/JointStateBroadcaster\n\n"
     << "    kontrolem_controller:\n"
     << "      type: kontrolem_ros2_control/KontrolemController\n\n"
     << "kontrolem_controller:\n"
     << "  ros__parameters:\n"
     << "    control_law: " << law << "\n"
     << "    actuated_joints: [";
  for (std::size_t i = 0; i < joint_names.size(); ++i) {
    os << (i ? ", " : "") << '"' << joint_names[i] << '"';
  }
  os << "]\n"
     << "    command_interface: effort\n"
     << "    state_position_interface: position\n"
     << "    state_velocity_interface: velocity\n"
     << "    safe_action: zero\n\n"
     << "    # Setpoint (Regulation): the configuration to hold, length nq = " << nq << ".\n"
     << "    q_ref: [";
  for (int i = 0; i < nq; ++i) os << (i ? ", " : "") << "0.0";
  os << "]\n"
     << "    v_ref: [";
  for (int i = 0; i < nq; ++i) os << (i ? ", " : "") << "0.0";
  os << "]\n\n"
     << "    # --- " << law << " parameters (defaults from its ParameterSpec) ---\n";
  for (const auto & d : spec) {
    os << "    # " << d.description << "\n"
       << "    " << d.name << ": " << value_str(d.default_value) << "\n";
  }
  return os.str();
}

std::string scaffold_launch(const std::string & urdf_file, const std::string & yaml_file)
{
  std::ostringstream os;
  os << "# Generated by `kontrolem_setup new`. Uses the kontrolem_bringup custom-sim\n"
     << "# harness (self-contained ros2_control sim); on a real robot, replace\n"
     << "# build_sim_launch with your hardware bring-up and keep the controllers YAML.\n"
     << "import os\n"
     << "import sys\n\n"
     << "sys.path.insert(0, os.path.dirname(__file__))\n"
     << "from _common import build_sim_launch  # noqa: E402\n\n\n"
     << "def generate_launch_description():\n"
     << "    return build_sim_launch(\n"
     << "        urdf_file=\"" << urdf_file << "\",\n"
     << "        controllers_yaml=\"" << yaml_file << "\",\n"
     << "    )\n";
  return os.str();
}

}  // namespace kontrolem_workbench
